/* Everything a crawler, an answer engine or a security scanner sees.
   These files are generated by tools/build-meta.js; if this suite fails after
   editing index.html, run `npm run build:meta` and commit the result. */
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const {JSDOM}=require('jsdom');
const PUB=path.join(__dirname,'..','public');
const read=f=>fs.readFileSync(path.join(PUB,f),'utf8');
const html=read('index.html');
let pass=0,fail=0;
const ok=(n,c)=>c?(pass++,console.log('  ✓ '+n)):(fail++,console.log('  ✗ '+n));

console.log('\n— structured data —');
const m=html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
ok('JSON-LD block present', !!m);
let g=null;
try{ g=JSON.parse(m[1]); ok('JSON-LD is valid JSON', true) }catch(e){ ok('JSON-LD is valid JSON', false) }
if(g){
  const byType=t=>g['@graph'].filter(n=>n['@type']===t);
  ok('declares Organization, WebSite and WebPage',
     byType('Organization').length===1&&byType('WebSite').length===1&&byType('WebPage').length===1);
  const faq=byType('FAQPage')[0];
  ok('objections published as an FAQPage', !!faq&&faq.mainEntity.length>=5);
  ok('every FAQ answer has real text', faq.mainEntity.every(q=>q.acceptedAnswer.text.length>100));
  const ev=byType('Event');
  ok('calendar published as Events', ev.length>=10);
  ok('events carry ISO dates', ev.every(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.startDate)));
  ok('Austin Pride is in the structured data', ev.some(e=>/Pride/i.test(e.name)));
  ok('sources published as citations', byType('WebPage')[0].citation.length>=8);
  const j=JSON.stringify(g);
  ok('no raw HTML leaked into values', !/<[a-z\/]/i.test(j));
  ok('no HTML entities leaked into values', !/&(amp|lt|gt|quot|nbsp|#\d+);/.test(j));
  ok('absolute URLs throughout', byType('Organization')[0].url.startsWith('https://'));
}

console.log('\n— crawler files —');
ok('sitemap.xml exists and is well formed', /<\?xml/.test(read('sitemap.xml'))&&/<loc>https:\/\//.test(read('sitemap.xml')));
ok('robots.txt points at the sitemap', /Sitemap: https:\/\/.*sitemap\.xml/.test(read('robots.txt')));
ok('llms.txt exists', fs.existsSync(path.join(PUB,'llms.txt')));
const llms=read('llms.txt');
ok('llms.txt states the mechanism', /sidewalk/i.test(llms)&&/roadway/i.test(llms));
ok('llms.txt carries the verified figures', /5,330/.test(llms)&&/170,000/.test(llms));
ok('llms.txt lists sources', /## Sources/.test(llms)&&/https:\/\//.test(llms));
ok('llms.txt asks summarisers to keep the framing', /non-adversarial/i.test(llms));
ok('404 page exists and is noindex', /noindex/.test(read('404.html')));
ok('404 routes people back', /href="\/"/.test(read('404.html')));
ok('favicon file exists for the 404 page', fs.existsSync(path.join(PUB,'favicon.svg')));

console.log('\n— headers —');
const h=read('_headers');
ok('CSP present', /Content-Security-Policy:/.test(h));
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
ok('exactly one inline script', scripts.length===1);
const want="sha256-"+crypto.createHash('sha256').update(scripts[0],'utf8').digest('base64');
ok('CSP hash matches the served script', h.includes(want));
ok('CSP has no unsafe-inline for scripts', !/script-src[^;]*unsafe-inline/.test(h));
ok('CSP allows only the two lookup endpoints',
   /connect-src[^;]*geocoding\.geo\.census\.gov/.test(h)&&
   /connect-src[^;]*data\.austintexas\.gov/.test(h)&&
   !/connect-src[^;]*\*/.test(h));
ok('CSP blocks object and base-uri', /object-src 'none'/.test(h)&&/base-uri 'none'/.test(h));
ok('HSTS set for a year', /Strict-Transport-Security: max-age=31536000/.test(h));
ok('no inline event handlers anywhere', !/ on(click|load|error|input|change)=/.test(html));

console.log('\n— analytics —');
ok('ships with nothing enabled', /ga4:\s*''/.test(html)&&/cfToken:\s*''/.test(html));
ok('no third-party script tags in the served HTML', !/<script[^>]+src="https:\/\/(?!fonts)/.test(html));
ok('Google is not permitted while GA is off',
   !/script-src[^;]*googletagmanager/.test(h)&&!/connect-src[^;]*google-analytics/.test(h));
ok('Cloudflare beacon is permitted so edge injection is not silently blocked',
   /script-src[^;]*static\.cloudflareinsights\.com/.test(h));
ok('Do Not Track is respected by default', /respectDNT:\s*true/.test(html));
ok('events are instrumented, not just pageviews',
   ['letter_generated','letter_copied','council_form_opened','template_copied','action_completed','calendar_added','district_found']
     .every(e=>html.includes("'"+e+"'")));
ok('tracking is a no-op when disabled', (()=>{
   const dm=new JSDOM(html,{runScripts:'dangerously',url:'https://x.test/',pretendToBeVisual:true});
   return dm.window.document.querySelectorAll('script[src*="googletagmanager"]').length===0})());
// the string appears in a comment explaining why it is absent; check for real use
ok('Vercel Analytics not actually wired up',
   !/src=["'][^"']*_vercel/.test(html) && !/fetch\(["']\/_vercel/.test(html) && !/@vercel\/analytics/.test(html));

console.log('\n— resilience without JavaScript —');
const rawDoc=new JSDOM(html).window.document;
const ns=rawDoc.querySelector('noscript');
ok('noscript fallback present', !!ns);
ok('fallback carries the core argument', /sidewalk/i.test(ns.textContent)&&/San Antonio/.test(ns.textContent));
ok('fallback gives a way to act', /austintexas\.gov\/email\/all-council-members/.test(ns.innerHTML));
ok('fallback carries a phone number', /tel:\+1512978/.test(ns.innerHTML));
ok('fallback cites sources', (ns.innerHTML.match(/https:\/\//g)||[]).length>=5);
ok('a script error reveals all panels', /js-failed/.test(html)&&/addEventListener\('error'/.test(html));

console.log('\n— accessibility detail —');
ok('slider announces its position', /aria-valuetext/.test(html));
ok('district result is announced', /id="distHint"[^>]*aria-live/.test(html));
ok('tabs use a single tab stop', (html.match(/data-tab="(play|write|act)" aria-selected="false" tabindex="-1"/g)||[]).length===3);
ok('safe-area insets for notched phones', /env\(safe-area-inset/.test(html));
ok('print styles present', /@media print/.test(html));

console.log('\n— contact and liveness —');
const liveDoc=new JSDOM(html,{runScripts:'dangerously',url:'https://x.test/',pretendToBeVisual:true}).window.document;
ok('a contact section exists', !!liveDoc.querySelector('#contact'));
ok('contact details render', liveDoc.querySelectorAll('.contactrow').length>=3);
ok('a press route is offered', /press\.html/.test(liveDoc.querySelector('#contactBox').innerHTML));
ok('corrections route to the issue template', /template=correction/.test(liveDoc.querySelector('#contactBox').innerHTML));
ok('footer links to contact', /href="#contact"/.test(html));
ok('liveness strip renders', !!liveDoc.querySelector('#pulse')&&liveDoc.querySelector('#pulse').children.length===3);
ok('petition figure is real and linked', /change\.org/.test(liveDoc.querySelector('#pulse').innerHTML)&&/5,330/.test(liveDoc.querySelector('#pulse').textContent));
ok('countdown is computed, not hardcoded', /pulseDays/.test(html));
ok('verification date is stamped by the build', /var VERIFIED='[0-9]/.test(html));
ok('verification line renders', /checked against its source on/.test(liveDoc.querySelector('#verified').textContent));
// the site's credibility depends on this: no invented counters
ok('no fabricated activity counters', !/letters sent|people took action|supporters so far|joined today/i.test(liveDoc.body.textContent));

console.log('\n— images and contact safety —');
ok('photo infrastructure exists but ships empty', /var PHOTOS=\[/.test(html)&&/PHOTOS=\[\s*\/\//.test(html.replace(/\n/g,'')));
ok('photo slot hidden until an image exists', liveDoc.querySelector('#heroPhoto').hidden===true);
ok('photos render with credit and licence', /class="credit"/.test(html)&&/p\.license/.test(html));
ok('photos use responsive picture with lazy loading', /<picture>/.test(html)&&/loading="lazy"/.test(html));
ok('no addresses published before they exist', /email:''/.test(html)&&/press:''/.test(html));
ok('falls back to a route that actually works', /discussions/.test(liveDoc.querySelector('#contactBox').innerHTML));

console.log('\n— press kit —');
const press=fs.readFileSync(path.join(PUB,'press.html'),'utf8');
const pd=new JSDOM(press).window.document;
ok('press kit exists', press.length>3000);
ok('every figure carries a source link', pd.querySelectorAll('.fact a[href^="https://"]').length>=5);
ok('quotes are provided', pd.querySelectorAll('.quote').length>=2);
ok('images are offered', pd.querySelectorAll('.asset img').length>=2);
ok('states plainly which images cannot be licensed', /cannot licence|cannot license/i.test(press));
ok('press has a working contact route', /mailto:press@/.test(press) || /discussions/.test(press));
ok('press kit promises no address it does not have', !/email address at the bottom/.test(press));
ok('links back to the site', /href="\/"/.test(press));

console.log('\n— head —');
const d=new JSDOM(html).window.document;
ok('title is descriptive', d.title.length>25&&d.title.length<70);
ok('meta description sized for search results', (()=>{const c=d.querySelector('meta[name=description]').content; return c.length>110&&c.length<330})());
ok('canonical present', !!d.querySelector('link[rel=canonical]'));
ok('og:url present', !!d.querySelector('meta[property="og:url"]'));
ok('og:image absolute', d.querySelector('meta[property="og:image"]').content.startsWith('https://'));
ok('lang set', d.documentElement.lang==='en');
ok('single h1', d.querySelectorAll('h1').length===1);
ok('preconnect to the font host', !!d.querySelector('link[rel=preconnect][href*="fonts.gstatic"]'));

console.log('\n— deep links —');
['case','play','write','act'].forEach(t=>{
  const dm=new JSDOM(html,{runScripts:'dangerously',url:'https://x.test/#'+t,pretendToBeVisual:true});
  // give the script a tick
  const res=()=>dm.window.document.querySelector('#p-'+t).classList.contains('on');
  setTimeout(()=>{},0);
  ok('#'+t+' opens its own tab', (()=>{ try{ return res() }catch(e){ return false } })());
});

setTimeout(()=>{
  console.log('\n'+(fail===0?'ALL '+pass+' PASSED':pass+' passed, '+fail+' FAILED'));
  process.exit(fail?1:0);
},400);
