/* Everything a crawler, an answer engine or a security scanner sees.
   These files are generated by tools/build-meta.js; if this suite fails after
   editing index.html, run `npm run build:meta` and commit the result. */
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const {JSDOM}=require('jsdom');
const PUB=path.join(__dirname,'..','public');
const read=f=>fs.readFileSync(path.join(PUB,f),'utf8');
const RAW=read('index.html');                        // byte-for-byte what ships
const B=require('./_boot');
const html=B.inline();                               // with site.css + site.js spliced in
let pass=0,fail=0;
const ok=(n,c)=>c?(pass++,console.log('  ✓ '+n)):(fail++,console.log('  ✗ '+n));

console.log('\n— structured data —');
/* Structured data must describe the page it sits on. The FAQ is on background,
   the events and the HowTo are on act. Markup on the wrong page is not a
   near-miss: it earns nothing and fails silently. */
const graphOf=f=>{
  const m=B.read(f).match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
  if(!m) return null;
  try{ return JSON.parse(m[1]) }catch(e){ return 'INVALID' }
};
const G={}; B.PAGES.forEach(f=>{ G[f]=graphOf(f) });
ok('every page carries a JSON-LD block', B.PAGES.every(f=>G[f]&&G[f]!=='INVALID'));
ok('every graph is valid JSON', B.PAGES.every(f=>G[f]!=='INVALID'));
const types=f=>(G[f]&&G[f]['@graph']||[]).map(n=>n['@type']);
const nodesOf=(f,t)=>(G[f]&&G[f]['@graph']||[]).filter(n=>n['@type']===t);

ok('home declares Organization and WebSite exactly once',
   nodesOf('index.html','Organization').length===1&&nodesOf('index.html','WebSite').length===1);
ok('Organization and WebSite are declared on one page only',
   B.PAGES.filter(f=>types(f).includes('Organization')).length===1);
ok('every page has breadcrumbs', B.PAGES.every(f=>nodesOf(f,'BreadcrumbList').length===1));
ok('inner pages breadcrumb back to home', B.PAGES.filter(f=>f!=='index.html').every(f=>{
  const c=nodesOf(f,'BreadcrumbList')[0];
  return c.itemListElement.length===2 && c.itemListElement[0].name==='Home';
}));
ok('every page declares a page-type node', B.PAGES.every(f=>
  ['WebPage','AboutPage','ContactPage'].some(t=>types(f).includes(t))));

const faq=nodesOf('background.html','FAQPage')[0];
ok('objections published as an FAQPage, on the page that shows them', !!faq&&faq.mainEntity.length>=5);
ok('the FAQ is not duplicated onto other pages',
   B.PAGES.filter(f=>types(f).includes('FAQPage')).length===1);
ok('every FAQ answer has real text', !!faq&&faq.mainEntity.every(q=>q.acceptedAnswer.text.length>100));

const ev=nodesOf('help.html','Event');
ok('calendar published as Events, on the page that lists them', ev.length>=10);
const il=nodesOf('help.html','ItemList')[0];
ok('the action list is published as an ItemList', !!il&&il.itemListElement.length===12);
ok('every action in the list is named', !!il&&il.itemListElement.every(x=>x.name&&x.name.length>5));
ok('events carry ISO dates', ev.every(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.startDate)));
ok('Austin Pride is in the structured data', ev.some(e=>/Pride/i.test(e.name)));
const ht=nodesOf('act.html','HowTo')[0];
ok('the letter builder is published as a HowTo', !!ht&&ht.step.length>=4);
ok('every HowTo step points somewhere real', !!ht&&ht.step.every(x=>/^https:\/\/[^#]+#?/.test(x.url)));
ok('the HowTo is honest about the time it takes', !!ht&&ht.totalTime==='PT5M');

ok('sources published as citations on the page that carries them',
   (nodesOf('background.html','AboutPage')[0].citation||[]).length>=8);
const j=B.PAGES.map(f=>JSON.stringify(G[f])).join(' ');
ok('no raw HTML leaked into values', !/<[a-z\/]/i.test(j));
ok('no HTML entities leaked into values', !/&(amp|lt|gt|quot|nbsp|#\d+);/.test(j));
ok('absolute URLs throughout', nodesOf('index.html','Organization')[0].url.startsWith('https://'));

console.log('\n— crawler files —');
ok('sitemap.xml exists and is well formed', /<\?xml/.test(read('sitemap.xml'))&&/<loc>https:\/\//.test(read('sitemap.xml')));
ok('robots.txt points at the sitemap', /Sitemap: https:\/\/.*sitemap\.xml/.test(read('robots.txt')));
ok('llms.txt exists', fs.existsSync(path.join(PUB,'llms.txt')));
const llms=read('llms.txt');
ok('llms.txt states the mechanism', /sidewalk/i.test(llms)&&/roadway/i.test(llms));
ok('llms.txt carries the verified figures', /5,330/.test(llms)&&/170,000/.test(llms));
ok('llms.txt lists sources', /## Sources/.test(llms)&&/https:\/\//.test(llms));
ok('llms.txt asks summarizers to keep the framing', /non-adversarial/i.test(llms));
ok('llms.txt maps every page', B.PAGES.every(f=>llms.includes(f==='index.html'?'.com/)':'/'+f+')')));
ok('404 page exists and is noindex', /noindex/.test(read('404.html')));
ok('404 routes people back', /href="\/"/.test(read('404.html')));
ok('favicon file exists for the 404 page', fs.existsSync(path.join(PUB,'favicon.svg')));

console.log('\n— headers —');
const h=read('_headers');
ok('CSP present', /Content-Security-Policy:/.test(h));
// CSS and behavior are shared files now, so there is no inline script left to
// hash: script-src 'self' covers it, which is both simpler and harder to break.
// The fixture in _boot.js splices those files back in, so these checks exist to
// make sure the shipped page really does reference them.
ok('no inline script remains', !/<script>[\s\S]*?<\/script>/.test(RAW));
ok('page links the shared stylesheet', RAW.includes(B.CSS_TAG));
ok('page links the shared script', RAW.includes(B.JS_TAG));
ok('both shared files exist and are non-trivial',
   B.read('site.css').length>10000 && B.read('site.js').length>10000);
ok('CSP script-src is self only', /script-src 'self'(?:;| https:\/\/static\.cloudflareinsights)/.test(h));
ok('CSP has no unsafe-inline for scripts', !/script-src[^;]*unsafe-inline/.test(h));
ok('CSP no longer carries a stale script hash', !/sha256-/.test(h));
// The page talks to nothing but its own origin now that the lookup is a worker
// route, so connect-src is the tightest it can be.
ok('CSP connect-src is self only',
   /connect-src 'self'(?:;| https:\/\/cloudflareinsights)/.test(h)&&
   !/connect-src[^;]*census/.test(h)&&
   !/connect-src[^;]*\*/.test(h));
ok('CSP blocks object and base-uri', /object-src 'none'/.test(h)&&/base-uri 'none'/.test(h));
ok('HSTS set for a year', /Strict-Transport-Security: max-age=31536000/.test(h));
ok('no inline event handlers anywhere', !/ on(click|load|error|input|change)=/.test(html));

console.log('\n— analytics —');
ok('ships with nothing enabled', /ga4:\s*''/.test(html)&&/cfToken:\s*''/.test(html));
ok('no third-party script tags in the served HTML', !/<script[^>]+src="https:\/\/(?!fonts)/.test(html));
ok('Google is not permitted while GA is off',
   !/script-src[^;]*googletagmanager/.test(h)&&!/connect-src[^;]*google-analytics/.test(h));
// cfAuto cannot work on *.workers.dev: edge injection requires a domain proxied
// through Cloudflare. So the CSP should only carry the beacon origin once a
// token is actually configured, and the two must never disagree.
(()=>{
  const tok=(html.match(/cfToken:\s*'([^']*)'/)||[])[1]||'';
  const auto=/cfAuto:\s*true/.test(html);
  const allowed=/script-src[^;]*static\.cloudflareinsights\.com/.test(h);
  ok('CSP and analytics config agree', allowed===!!(tok||auto));
  ok('no analytics origin is opened while none is configured', (tok||auto)?true:!allowed);
})();
ok('Do Not Track is respected by default', /respectDNT:\s*true/.test(html));
ok('events are instrumented, not just pageviews',
   ['letter_generated','letter_copied','council_form_opened','template_copied','action_completed','calendar_added','district_found']
     .every(e=>html.includes("'"+e+"'")));
ok('tracking is a no-op when disabled', (()=>{
   const dm=new JSDOM(html,{runScripts:'dangerously',url:'https://x.test/',pretendToBeVisual:true});
   return dm.window.document.querySelectorAll('script[src*="googletagmanager"]').length===0})());
// the string appears in a comment explaining why it is absent; check for real use
ok('Vercel Analytics not actually wired up',
   !/src=["'][^"']*_vercel/.test(html) && !/fetch\(["']\/_vercel/.test(html) && !/@vercel\/analytics/.test(html));

console.log('\n— resilience without JavaScript —');
const rawDoc=new JSDOM(html).window.document;
const ns=rawDoc.querySelector('noscript');
ok('noscript fallback present', !!ns);
ok('fallback carries the core argument', /sidewalk/i.test(ns.textContent)&&/San Antonio/.test(ns.textContent));
ok('fallback gives a way to act', /austintexas\.gov\/email\/all-council-members/.test(ns.innerHTML));
ok('fallback carries a phone number', /tel:\+1512978/.test(ns.innerHTML));
ok('fallback cites sources', (ns.innerHTML.match(/https:\/\//g)||[]).length>=5);
ok('a script error reveals all panels', /js-failed/.test(html)&&/addEventListener\('error'/.test(html));

console.log('\n— accessibility detail —');
ok('slider announces its position', /aria-valuetext/.test(html));
ok('district result is announced', /id="distHint"[^>]*aria-live/.test(B.read('act.html')));
// tabs are gone; the equivalent promise is that the nav is a plain list of
// links, which needs no roving tabindex to be keyboard-usable at all
ok('nav needs no ARIA to be keyboard usable',
   B.PAGES.every(f=>{const n=B.read(f); return /<nav class="mainnav"/.test(n) && !/role="tab"/.test(n)}));
ok('safe-area insets for notched phones', /env\(safe-area-inset/.test(html));
ok('print styles present', /@media print/.test(html));

console.log('\n— contact and liveness —');
const liveDoc=new JSDOM(B.inline('contact.html'),{runScripts:'dangerously',url:'https://x.test/contact.html',pretendToBeVisual:true}).window.document;
ok('a contact section exists', !!liveDoc.querySelector('#contact'));
ok('contact details render', liveDoc.querySelectorAll('.contactrow').length>=3);
ok('a press route is offered', /press\.html/.test(liveDoc.querySelector('#contactBox').innerHTML));
// the chooser works whether or not a template parses; ?template= silently
// falls back to a 404 if the YAML is ever malformed
ok('corrections route to the issue chooser', /issues\/new\/choose/.test(liveDoc.querySelector('#contactBox').innerHTML));
ok('every footer links to the contact page', B.PAGES.every(f=>/href="\/contact\.html"/.test(B.read(f))));
// the liveness strip is part of the hero, so it lives on the home page.
// it fills in on a timer, so these are asserted at the end of the run.
const homeDoc=new JSDOM(B.inline('index.html'),{runScripts:'dangerously',url:'https://x.test/',pretendToBeVisual:true}).window.document;
ok('momentum strip is on the home page', homeDoc.querySelectorAll('.mo').length===3);
ok('countdown is computed, not hardcoded', /pulseDays/.test(html));
ok('verification date is stamped by the build', /var VERIFIED='[0-9]/.test(html));
ok('verification line renders', /checked against its source on/.test(liveDoc.querySelector('#verified').textContent));
// the site's credibility depends on this: no invented counters
ok('no fabricated activity counters', !/letters sent|people took action|supporters so far|joined today/i.test(liveDoc.body.textContent));

console.log('\n— images and contact safety —');
ok('photo infrastructure exists but ships empty', /var PHOTOS=\[/.test(html)&&/PHOTOS=\[\s*\/\//.test(html.replace(/\n/g,'')));
ok('photo slot hidden until an image exists', homeDoc.querySelector('#heroPhoto').hidden===true);
ok('photos render with credit and licence', /class="credit"/.test(html)&&/p\.license/.test(html));
ok('photos use responsive picture with lazy loading', /<picture>/.test(html)&&/loading="lazy"/.test(html));
ok('no addresses published before they exist', /email:''/.test(html)&&/press:''/.test(html));
ok('falls back to a route that actually works', /discussions/.test(liveDoc.querySelector('#contactBox').innerHTML));

console.log('\n— the build is reproducible —');
/* public/*.html is generated from src/pages by tools/build-pages.js. Editing a
   generated file directly works right up until the next build silently reverts
   it, so check that what shipped still contains what the source says.

   This deliberately does not run the build: doing that mid-suite rewrites files
   the other suites are reading, which turns one honest failure into four
   confusing ones. */
(()=>{
  const missing=B.PAGES.filter(f=>{
    const body=fs.readFileSync(path.join(__dirname,'..','src','pages',f),'utf8').trim();
    const first=body.split('\n').find(l=>l.trim());
    const last=body.split('\n').reverse().find(l=>l.trim());
    const out=B.read(f);
    return !out.includes(first.trim()) || !out.includes(last.trim());
  });
  ok('every shipped page still contains its source body'+(missing.length?' (stale: '+missing.join(', ')+')':''), missing.length===0);
})();
ok('page bodies are the editable source', B.PAGES.every(f=>fs.existsSync(path.join(__dirname,'..','src','pages',f))));
ok('the chrome is defined once', /const nav = current =>/.test(fs.readFileSync(path.join(__dirname,'..','tools','build-pages.js'),'utf8')));
ok('no page carries its own <style> block', B.PAGES.every(f=>!/<style>/.test(B.read(f))));
ok('every page loads the one stylesheet', B.PAGES.every(f=>B.read(f).includes(B.CSS_TAG)));

console.log('\n— press kit —');
const press=fs.readFileSync(path.join(PUB,'press.html'),'utf8');
const pd=new JSDOM(press).window.document;
ok('press kit exists', press.length>3000);
ok('every figure carries a source link', pd.querySelectorAll('.contact a[href^="https://"]').length>=5);
ok('quotes are provided', pd.querySelectorAll('.script').length>=2);
ok('images are offered', pd.querySelectorAll('.asset img').length>=2);
ok('states plainly which images cannot be licensed', /cannot licence|cannot license/i.test(press));
ok('press has a working contact route', /mailto:press@/.test(press) || /discussions/.test(press));
ok('press kit promises no address it does not have', !/email address at the bottom/.test(press));
ok('links back to the site', /href="\/"/.test(press));

console.log('\n— head —');
const d=new JSDOM(B.read('index.html')).window.document;
ok('title is descriptive', d.title.length>25&&d.title.length<70);
ok('meta description sized for search results', (()=>{const c=d.querySelector('meta[name=description]').content; return c.length>110&&c.length<330})());
ok('canonical present', !!d.querySelector('link[rel=canonical]'));
ok('og:url present', !!d.querySelector('meta[property="og:url"]'));
ok('og:image absolute', d.querySelector('meta[property="og:image"]').content.startsWith('https://'));
ok('lang set', d.documentElement.lang==='en');
ok('single h1', d.querySelectorAll('h1').length===1);
ok('preconnect to the font host', !!d.querySelector('link[rel=preconnect][href*="fonts.gstatic"]'));

console.log('\n— deep links —');
// Every tab is now a URL, and the old hashes still resolve to the right one.
const JS=B.read('site.js');
[['case','/background.html'],['play','/act.html#asks'],
 ['write','/act.html#letter'],['act','/act.html']].forEach(([t,to])=>{
  ok('#'+t+' still resolves to '+to, JS.includes("'"+to+"'"));
});
ok('old hashes redirect rather than dead-end', /location\.replace\(PAGE_FOR\[h\]\)/.test(JS));
ok('every page is in the sitemap', (()=>{const sm=B.read('sitemap.xml');
  return B.PAGES.every(f=>sm.includes(f==='index.html'?'.com/</loc>':'/'+f))})());
ok('every page declares its own canonical', (()=>{
  const set=new Set(B.PAGES.map(f=>(B.read(f).match(/rel="canonical" href="([^"]+)"/)||[])[1]));
  return set.size===B.PAGES.length && ![...set].includes(undefined)})());
ok('every page has a distinct title and description', (()=>{
  const t=new Set(B.PAGES.map(f=>(B.read(f).match(/<title>([^<]*)<\/title>/)||[])[1]));
  const dsc=new Set(B.PAGES.map(f=>(B.read(f).match(/name="description" content="([^"]*)"/)||[])[1]));
  return t.size===B.PAGES.length && dsc.size===B.PAGES.length})());

setTimeout(()=>{
  const pu=homeDoc.querySelector('#pulse');
  ok('liveness strip renders', !!pu && pu.children.length===3);
  ok('petition figure is real and linked', !!pu && /change\.org/.test(pu.innerHTML) && /5,330/.test(pu.textContent));
  console.log('\n'+(fail===0?'ALL '+pass+' PASSED':pass+' passed, '+fail+' FAILED'));
  process.exit(fail?1:0);
},400);
